### ISSUE TITLE
more empirical results are expected

### ISSUE THREAD

**Issue by alphadl** [anoidgit/transformer#2]
Hi, Hongfei and Qiuhui, Thanks for your efforts~ 

From your description in paper, this implementation achieves 28.07 on WMT'14 ENDE. It's great~ Have you try other datasets to validate its effectiveness? Also, have you reproduced the followig variants with your code?  i.e., [Hier*](https://www.aclweb.org/anthology/D18-1457/), [TA](https://aclweb.org/anthology/D18-1338), [SC](https://www.aclweb.org/anthology/P19-1624/), [DOC](https://www.aclweb.org/anthology/D18-1049/)

**Comment by anoidgit** [comment]
@alphadl 
Hi, thanks a lot for your attention.
we got some comparable BLEU after implementing them, we also have results on the other datasets but not reported in the draft paper.
Unfortunately, we do not have the results of these models of the current commit, as we merged lots of features into the project  and tuned many detailed configurations after the implementation of these approaches, neither do we have time to carefully maintain all these features, nor do we have GPU resources to run all related features after every commits. We also cannot access the original datasets of some papers.

**Comment by alphadl** [comment]
@anoidgit After EMNLP ddl, I would like to kindly reproduce the results of your implemented methods (Hier/ TA/ SC/ DOC ... ) on EN-DE dataset., such that this repository draw more NLPer's attention.

**Comment by anoidgit** [comment]
@alphadl It is really kind of you, but I personally suggest they are more examples to show the others how to extend this project or how to implement their own ideas based on it than reproducing these approaches. The baseline is already high for productive use, and I do not see any other values unless you want to use these approaches as your research baseline.

**Comment by alphadl** [comment]
I see ~ agree with you ! I will close this issue
